# Generated by Django 5.2.7 on 2026-04-20 17:32

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=256)),
                ('avatar', models.URLField(blank=True, max_length=1024)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('simple_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('reset_password', 'Reset Password')], max_length=16)),
                ('is_used', models.BooleanField(default=False)),
                ('expire_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_verification',
                'indexes': [models.Index(fields=['email', 'purpose'], name='idx_ev_email_purpose'), models.Index(fields=['expire_at'], name='idx_ev_expire_at')],
            },
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('doing', 'Doing'), ('wish', 'Wish'), ('done', 'Done'), ('on_hold', 'On Hold'), ('drop', 'Drop')], max_length=16)),
                ('simple_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('comment', models.TextField(blank=True)),
                ('watch_start_date', models.CharField(blank=True, max_length=16)),
                ('watch_end_date', models.CharField(blank=True, max_length=16)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='index.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subject',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('is_spoiler', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.usersubject')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('relation', models.CharField(blank=True, max_length=256)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.collection')),
                ('user_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='users.usersubject')),
            ],
            options={
                'db_table': 'collection_item',
            },
        ),
        migrations.CreateModel(
            name='UserSubjectRatingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=256)),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('user_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_detail', to='users.usersubject')),
            ],
            options={
                'db_table': 'user_subject_rating_detail',
            },
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tag',
            },
        ),
        migrations.CreateModel(
            name='UserSubjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='users.usersubject')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relations', to='users.usertag')),
            ],
            options={
                'db_table': 'user_subject_tag',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user'], name='idx_collection_user'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.CheckConstraint(condition=models.Q(('simple_rating__gte', 1), ('simple_rating__lte', 5)), name='ck_collection_simple_rating'),
        ),
        migrations.AddIndex(
            model_name='usersubject',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='idx_user_status_updated'),
        ),
        migrations.AddIndex(
            model_name='usersubject',
            index=models.Index(fields=['user', '-updated_at'], name='idx_user_updated'),
        ),
        migrations.AddIndex(
            model_name='usersubject',
            index=models.Index(fields=['user', '-simple_rating'], name='idx_user_simple_rating'),
        ),
        migrations.AddIndex(
            model_name='usersubject',
            index=models.Index(fields=['user', '-rating'], name='idx_user_rating'),
        ),
        migrations.AddIndex(
            model_name='usersubject',
            index=models.Index(fields=['user', 'watch_end_date'], name='idx_user_watch_end_date'),
        ),
        migrations.AddIndex(
            model_name='usersubject',
            index=models.Index(fields=['subject'], name='idx_subject'),
        ),
        migrations.AddIndex(
            model_name='usersubject',
            index=models.Index(fields=['subject', '-simple_rating'], name='idx_subject_simple_rating'),
        ),
        migrations.AddIndex(
            model_name='usersubject',
            index=models.Index(fields=['status'], name='idx_status'),
        ),
        migrations.AddConstraint(
            model_name='usersubject',
            constraint=models.UniqueConstraint(fields=('user', 'subject'), name='uq_user_subject'),
        ),
        migrations.AddConstraint(
            model_name='usersubject',
            constraint=models.CheckConstraint(condition=models.Q(('simple_rating__gte', 1), ('simple_rating__lte', 5)), name='ck_simple_rating'),
        ),
        migrations.AddConstraint(
            model_name='usersubject',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 0), ('rating__lte', 10)), name='ck_rating'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-created_at'], name='idx_review_created'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection'], name='idx_ci_collection'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['user_subject'], name='idx_ci_user_subject'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'user_subject'), name='uq_collection_user_subject'),
        ),
        migrations.AddConstraint(
            model_name='usersubjectratingdetail',
            constraint=models.UniqueConstraint(fields=('user_subject', 'key'), name='uq_user_subject_key'),
        ),
        migrations.AddConstraint(
            model_name='usersubjectratingdetail',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0), ('value__lte', 10)), name='ck_rating_value'),
        ),
        migrations.AddIndex(
            model_name='usertag',
            index=models.Index(fields=['user'], name='user_tag_user_id_0fedef_idx'),
        ),
        migrations.AddIndex(
            model_name='usertag',
            index=models.Index(fields=['name'], name='user_tag_name_00f993_idx'),
        ),
        migrations.AddConstraint(
            model_name='usertag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uq_user_tag'),
        ),
        migrations.AddConstraint(
            model_name='usersubjecttag',
            constraint=models.UniqueConstraint(fields=('user_subject', 'tag'), name='uq_user_subject_tag'),
        ),
    ]
