# Generated by Django 5.2.7 on 2026-05-10 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEpisodeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user_episode_progress',
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_follow',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=256, unique=True)),
                ('avatar', models.URLField(blank=True, max_length=1024)),
                ('bio', models.TextField(blank=True)),
                ('theme_color', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='idx_user_email',
            old_name='user_email_7bbb4c_idx',
        ),
        migrations.RenameIndex(
            model_name='usertag',
            new_name='idx_user_tag_user',
            old_name='user_tag_user_id_0fedef_idx',
        ),
        migrations.RenameIndex(
            model_name='usertag',
            new_name='idx_user_tag_name',
            old_name='user_tag_name_00f993_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userepisodeprogress',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_progress', to='index.episode'),
        ),
        migrations.AddField(
            model_name='userepisodeprogress',
            name='user_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_progress', to='users.usersubject'),
        ),
        migrations.AddField(
            model_name='userfollow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfollow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='userepisodeprogress',
            constraint=models.UniqueConstraint(fields=('user_subject', 'episode'), name='uq_user_subject_episode'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['follower'], name='idx_user_follower'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['following'], name='idx_user_following'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='uq_follow'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='ck_no_self_follow'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['nickname'], name='idx_user_nickname'),
        ),
    ]
