# Generated by Django 5.2.7 on 2026-05-11 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('users', '0003_userepisodeprogress_userfollow_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='ck_collection_simple_rating',
        ),
        migrations.RemoveConstraint(
            model_name='usersubject',
            name='ck_simple_rating',
        ),
        migrations.RemoveConstraint(
            model_name='usersubject',
            name='ck_rating',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='usersubjectratingdetail',
            name='user_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_details', to='users.usersubject'),
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.CheckConstraint(condition=models.Q(('simple_rating__isnull', True), models.Q(('simple_rating__gte', 1), ('simple_rating__lte', 5)), _connector='OR'), name='ck_collection_simple_rating'),
        ),
        migrations.AddConstraint(
            model_name='usersubject',
            constraint=models.CheckConstraint(condition=models.Q(('simple_rating__isnull', True), models.Q(('simple_rating__gte', 1), ('simple_rating__lte', 5)), _connector='OR'), name='ck_simple_rating'),
        ),
        migrations.AddConstraint(
            model_name='usersubject',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 0), ('rating__lte', 10)), _connector='OR'), name='ck_rating'),
        ),
    ]
