# Generated by Django 5.2.7 on 2026-05-11 20:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_collection_ck_collection_simple_rating_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userfollow',
            name='idx_user_follower',
        ),
        migrations.RemoveIndex(
            model_name='userfollow',
            name='idx_user_following',
        ),
        migrations.AddField(
            model_name='userfollow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['follower', '-created_at'], name='idx_uf_follower_created'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['following', '-created_at'], name='idx_uf_following_created'),
        ),
    ]
