# Generated by Django 5.2.7 on 2026-05-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userfollow_idx_user_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
