# Generated by Django 5.2.7 on 2026-05-11 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_review_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('user_subject_created', 'User subject created'), ('user_subject_updated', 'User subject updated'), ('review_created', 'Review created'), ('collection_created', 'Collection created'), ('collection_item_added', 'Collection item added'), ('user_followed', 'User followed')], max_length=64)),
                ('message', models.CharField(blank=True, max_length=512)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.collection')),
                ('collection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.collectionitem')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.review')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('user_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.usersubject')),
            ],
            options={
                'db_table': 'activity',
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_activity_user_created'), models.Index(fields=['activity_type', '-created_at'], name='idx_activity_type_created'), models.Index(fields=['is_public', '-created_at'], name='idx_activity_public_created')],
            },
        ),
    ]
