# Generated by Django 5.2.7 on 2026-05-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='message',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
