# Generated by Django 5.2.7 on 2026-05-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_activity_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['user', 'is_public'], name='idx_collection_public'),
        ),
    ]
