# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_collection_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("en-US", "English"),
                    ("zh-CN", "Chinese"),
                    ("ja-JP", "Japanese"),
                ],
                default="auto",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="appearance",
            field=models.CharField(
                choices=[
                    ("auto", "Auto"),
                    ("light", "Light"),
                    ("dark", "Dark"),
                ],
                default="auto",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="theme_color",
            field=models.CharField(default="#7F6FB0", max_length=16),
        ),
    ]
