# Generated by Django 5.2.7 on 2026-06-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='userfollow',
            name='following',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='UserFollow',
        ),
    ]
