# Generated by Django 5.2.16 on 2026-07-27

from django.contrib.postgres.operations import (
    AddIndexConcurrently,
    RemoveIndexConcurrently,
)
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("users", "0012_remove_userfollow_follower_and_more"),
    ]

    operations = [
        RemoveIndexConcurrently(
            model_name="emailverification",
            name="idx_ev_email_purpose",
        ),
        RemoveIndexConcurrently(
            model_name="user",
            name="idx_user_email",
        ),
        AddIndexConcurrently(
            model_name="emailverification",
            index=models.Index(
                fields=["email", "purpose", "-created_at"],
                name="idx_ev_email_purpose",
            ),
        ),
    ]
