# Generated by Django 5.2.16 on 2026-08-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_airingevent_appearance_contentrating_entity_credit_and_more'),
        ('users', '0015_use_native_watch_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('dropped', 'Dropped')], max_length=16)),
                ('language', models.CharField(blank=True, max_length=35)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('note', models.TextField(blank=True)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_release',
            },
        ),
        migrations.AddField(
            model_name='usersubject',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_library_entries', to='index.entity'),
        ),
        migrations.AddConstraint(
            model_name='usersubject',
            constraint=models.UniqueConstraint(condition=models.Q(('entity__isnull', False)), fields=('user', 'entity'), name='uq_user_library_entity'),
        ),
        migrations.AddField(
            model_name='userrelease',
            name='library_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_states', to='users.usersubject'),
        ),
        migrations.AddField(
            model_name='userrelease',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_states', to='index.release'),
        ),
        migrations.AddConstraint(
            model_name='userrelease',
            constraint=models.UniqueConstraint(fields=('library_entry', 'release'), name='uq_user_library_release'),
        ),
        migrations.AddConstraint(
            model_name='userrelease',
            constraint=models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('completed_at__isnull', True), ('started_at__lte', models.F('completed_at')), _connector='OR'), name='ck_user_release_date_range'),
        ),
    ]
