# Generated by Django 5.2.16 on 2026-08-12 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_airingevent_appearance_contentrating_entity_credit_and_more'),
        ('users', '0016_userrelease_usersubject_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubject',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='index.subject'),
        ),
    ]
