# Generated by Django 5.2.17 on 2026-08-21 06:51

import django.db.models.deletion
from django.db import migrations, models


def copy_episode_entities(apps, schema_editor):
    UserEpisodeProgress = apps.get_model("users", "UserEpisodeProgress")
    Episode = apps.get_model("index", "Episode")
    episode_entities = {
        episode_id: entity_id
        for episode_id, entity_id in Episode.objects.filter(
            entity_id__isnull=False
        ).values_list("id", "entity_id")
    }
    for progress in UserEpisodeProgress.objects.iterator(chunk_size=1000):
        entity_id = episode_entities.get(progress.episode_id)
        if entity_id is not None:
            progress.episode_entity_id = entity_id
            progress.save(update_fields=["episode_entity_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_term_alias'),
        ('users', '0018_userprofile_adult_content_confirmed_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userepisodeprogress',
            name='uq_user_subject_episode',
        ),
        migrations.AddField(
            model_name='userepisodeprogress',
            name='episode_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_episode_progress', to='index.entity'),
        ),
        migrations.RunPython(copy_episode_entities, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='userepisodeprogress',
            name='episode',
        ),
        migrations.AddConstraint(
            model_name='userepisodeprogress',
            constraint=models.UniqueConstraint(fields=('user_subject', 'episode_entity'), name='uq_user_subject_episode'),
        ),
    ]
