# Generated by Django 5.2.17 on 2026-08-21 07:24

from django.db import migrations


def copy_subject_entities(apps, schema_editor):
    UserSubject = apps.get_model("users", "UserSubject")
    Entity = apps.get_model("index", "Entity")
    entity_ids = set(Entity.objects.values_list("id", flat=True))

    for entry in UserSubject.objects.filter(entity__isnull=True).iterator():
        if entry.subject_id in entity_ids:
            UserSubject.objects.filter(pk=entry.pk).update(entity_id=entry.subject_id)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_userepisodeprogress_uq_user_subject_episode_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usersubject',
            name='uq_user_subject',
        ),
        migrations.RemoveIndex(
            model_name='usersubject',
            name='idx_subject_simple_rating',
        ),
        migrations.RunPython(copy_subject_entities, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='usersubject',
            name='subject',
        ),
    ]
