# Generated by Django 5.2.16 on 2026-08-11 08:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0008_airingevent_appearance_contentrating_entity_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_case', models.CharField(max_length=64, unique=True)),
                ('policy_version', models.CharField(max_length=64)),
                ('shadow_mode', models.BooleanField(default=True)),
                ('minimum_score', models.DecimalField(decimal_places=4, default='0.9950', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('minimum_margin', models.DecimalField(decimal_places=4, default='0.0500', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('minimum_evidence_types', models.PositiveSmallIntegerField(default=2)),
                ('required_evaluation_precision', models.DecimalField(decimal_places=4, default='0.9990', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ai_policy',
            },
        ),
        migrations.CreateModel(
            name='AIEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use_case', models.CharField(max_length=64)),
                ('policy_version', models.CharField(max_length=64)),
                ('dataset_version', models.CharField(max_length=64)),
                ('sample_count', models.PositiveIntegerField()),
                ('precision', models.DecimalField(decimal_places=4, max_digits=5)),
                ('recall', models.DecimalField(decimal_places=4, max_digits=5)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ai_evaluation_run',
                'indexes': [models.Index(fields=['use_case', 'policy_version', '-created_at'], name='idx_ai_evaluation_latest')],
            },
        ),
        migrations.CreateModel(
            name='AIRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use_case', models.CharField(max_length=64)),
                ('provider', models.CharField(max_length=64)),
                ('model', models.CharField(max_length=256)),
                ('prompt_version', models.CharField(max_length=64)),
                ('input_hash', models.CharField(max_length=64)),
                ('input_metadata', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('abstained', 'Abstained')], default='queued', max_length=16)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ai_run',
                'indexes': [models.Index(fields=['use_case', '-created_at'], name='idx_ai_run_use_case'), models.Index(fields=['status', 'created_at'], name='idx_ai_run_status'), models.Index(fields=['input_hash'], name='idx_ai_run_input_hash')],
            },
        ),
        migrations.CreateModel(
            name='AIProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proposal_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('abstained', 'Abstained')], default='pending', max_length=16)),
                ('policy_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('match_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_proposals', to='index.matchcandidate')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='ai.airun')),
            ],
            options={
                'db_table': 'ai_proposal',
                'indexes': [models.Index(fields=['proposal_type', 'status'], name='idx_ai_proposal_status')],
            },
        ),
    ]
