# Generated by Django 5.2.17 on 2026-08-25 08:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiproposal_source_observation_and_more'),
        ('index', '0019_remove_termalias_uq_term_alias_key_termalias_origin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('web_page', 'Web page'), ('search_result', 'Search result'), ('internal_snapshot', 'Internal snapshot')], max_length=32)),
                ('source_url', models.URLField(blank=True, max_length=2048)),
                ('content_hash', models.CharField(max_length=64)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('byte_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('object_key', models.CharField(blank=True, max_length=1024)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('license_info', models.CharField(blank=True, max_length=512)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'source_artifact',
            },
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_session',
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('admin_sync', 'Admin sync'), ('admin_enrich', 'Admin enrichment'), ('user_agent', 'User agent'), ('evaluation', 'Evaluation')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting', 'Waiting'), ('paused', 'Paused'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('trace_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('checkpoint', models.JSONField(blank=True, default=dict)),
                ('budget', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_agent_runs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ai.agentsession')),
            ],
            options={
                'db_table': 'agent_run',
            },
        ),
        migrations.CreateModel(
            name='AgentStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('plan', 'Plan'), ('retrieve', 'Retrieve'), ('tool', 'Tool'), ('model', 'Model'), ('skill', 'Skill'), ('validate', 'Validate'), ('approval', 'Approval'), ('apply', 'Apply'), ('verify', 'Verify')], max_length=16)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('waiting', 'Waiting'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('skill_name', models.CharField(blank=True, max_length=128)),
                ('skill_version', models.CharField(blank=True, max_length=64)),
                ('input_hash', models.CharField(blank=True, max_length=64)),
                ('input', models.JSONField(blank=True, default=dict)),
                ('output', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ai.agentstep')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ai.agentrun')),
            ],
            options={
                'db_table': 'agent_step',
                'ordering': ['run', 'sequence'],
            },
        ),
        migrations.AddField(
            model_name='airun',
            name='agent_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_invocations', to='ai.agentstep'),
        ),
        migrations.CreateModel(
            name='AIClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_type', models.CharField(max_length=64)),
                ('predicate_slug', models.CharField(blank=True, max_length=128)),
                ('proposed_value', models.JSONField()),
                ('model_confidence', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('evidence_strength', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('calibrated_confidence', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], default='proposed', max_length=16)),
                ('policy_decision', models.CharField(blank=True, max_length=64)),
                ('policy_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='ai.aiproposal')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='ai.agentstep')),
                ('target_entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ai_claims', to='index.entity')),
            ],
            options={
                'db_table': 'ai_claim',
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('admin_review', 'Admin review'), ('user_confirm', 'User confirmation')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('summary', models.TextField()),
                ('diff', models.JSONField(default=dict)),
                ('risk_level', models.CharField(max_length=16)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_approvals', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='ai.agentrun')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='ai.agentstep')),
            ],
            options={
                'db_table': 'approval_request',
            },
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locator', models.CharField(max_length=512)),
                ('excerpt', models.TextField(blank=True)),
                ('excerpt_hash', models.CharField(blank=True, max_length=64)),
                ('relevance', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='ai.aiclaim')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim_evidence_links', to='index.observation')),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim_evidence_links', to='ai.sourceartifact')),
            ],
            options={
                'db_table': 'claim_evidence',
            },
        ),
        migrations.CreateModel(
            name='ToolInvocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=128)),
                ('tool_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=16)),
                ('parameters', models.JSONField(default=dict)),
                ('parameter_hash', models.CharField(max_length=64)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=128)),
                ('permission_scope', models.CharField(max_length=64)),
                ('risk_level', models.CharField(max_length=16)),
                ('has_side_effects', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tool_invocations', to='ai.agentstep')),
            ],
            options={
                'db_table': 'tool_invocation',
            },
        ),
        migrations.AddField(
            model_name='sourceartifact',
            name='tool_invocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='ai.toolinvocation'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['user', '-updated_at'], name='idx_agent_session_user'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['kind', 'status'], name='idx_agent_run_kind_status'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status', '-created_at'], name='idx_agent_run_status_created'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uq_agent_run_idempotency'),
        ),
        migrations.AddIndex(
            model_name='agentstep',
            index=models.Index(fields=['kind', 'status'], name='idx_agent_step_kind_status'),
        ),
        migrations.AddConstraint(
            model_name='agentstep',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='uq_agent_step_run_sequence'),
        ),
        migrations.AddIndex(
            model_name='aiclaim',
            index=models.Index(fields=['target_entity', 'claim_type'], name='idx_ai_claim_target_type'),
        ),
        migrations.AddIndex(
            model_name='aiclaim',
            index=models.Index(fields=['status', '-created_at'], name='idx_ai_claim_status'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'kind'], name='idx_approval_req_status_kind'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['reviewer', 'status'], name='idx_approval_req_reviewer'),
        ),
        migrations.AddConstraint(
            model_name='claimevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artifact__isnull', True), ('observation__isnull', False)), models.Q(('artifact__isnull', False), ('observation__isnull', True)), _connector='OR'), name='ck_claim_evidence_one_source'),
        ),
        migrations.AddConstraint(
            model_name='claimevidence',
            constraint=models.UniqueConstraint(fields=('claim', 'observation', 'artifact', 'locator'), name='uq_claim_evidence_source_locator', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='toolinvocation',
            index=models.Index(fields=['step', 'tool_name'], name='idx_tool_invocation_step'),
        ),
        migrations.AddIndex(
            model_name='toolinvocation',
            index=models.Index(fields=['status', '-created_at'], name='idx_tool_invocation_status'),
        ),
        migrations.AddConstraint(
            model_name='toolinvocation',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tool_name', 'idempotency_key'), name='uq_tool_invocation_idempotency'),
        ),
        migrations.AddIndex(
            model_name='sourceartifact',
            index=models.Index(fields=['content_hash'], name='idx_source_artifact_hash'),
        ),
        migrations.AddIndex(
            model_name='sourceartifact',
            index=models.Index(fields=['kind', '-fetched_at'], name='idx_src_artifact_kind_fetch'),
        ),
    ]
