# Generated by Django 5.2.17 on 2026-08-25 09:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_sourceartifact_agentsession_agentrun_agentstep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='agentrun',
            name='uq_agent_run_idempotency',
        ),
        migrations.RemoveConstraint(
            model_name='toolinvocation',
            name='uq_tool_invocation_idempotency',
        ),
        migrations.AddField(
            model_name='agentrun',
            name='idempotency_scope',
            field=models.CharField(default='system', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_scope', 'idempotency_key'), name='uq_agent_run_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='toolinvocation',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tool_name', 'tool_version', 'idempotency_scope', 'idempotency_key'), name='uq_tool_invocation_idempotency'),
        ),
    ]
