# Generated by Django 5.2.7 on 2026-06-02 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0005_calendarsubject_collection_doing'),
        ('users', '0012_remove_userfollow_follower_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('post_created', 'Post created'), ('user_subject_created', 'User subject created'), ('user_subject_updated', 'User subject updated'), ('review_created', 'Review created'), ('collection_created', 'Collection created'), ('collection_item_added', 'Collection item added'), ('comment_created', 'Comment created'), ('user_followed', 'User followed')], max_length=64)),
                ('message', models.CharField(blank=True, max_length=1024)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], default='public', max_length=16)),
                ('feed_policy', models.CharField(choices=[('hidden', 'Hidden'), ('normal', 'Normal'), ('featured', 'Featured')], default='normal', max_length=16)),
                ('group_key', models.CharField(blank=True, max_length=256)),
                ('dedupe_key', models.CharField(blank=True, max_length=256)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.collection')),
                ('collection_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.collectionitem')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.review')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='index.subject')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('user_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.usersubject')),
            ],
            options={
                'db_table': 'community_activity',
            },
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], default='public', max_length=16)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('reaction_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.activity')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='users.collection')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='community.communitycomment')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_comments', to='users.review')),
            ],
            options={
                'db_table': 'community_comment',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='community.communitycomment'),
        ),
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('status', 'Status'), ('subject', 'Subject')], default='status', max_length=16)),
                ('content', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('private', 'Private')], default='public', max_length=16)),
                ('feed_policy', models.CharField(choices=[('hidden', 'Hidden'), ('normal', 'Normal'), ('featured', 'Featured')], default='normal', max_length=16)),
                ('is_spoiler', models.BooleanField(default=False)),
                ('is_nsfw', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('reaction_count', models.PositiveIntegerField(default=0)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_posts', to='index.subject')),
            ],
            options={
                'db_table': 'community_post',
            },
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.communitypost'),
        ),
        migrations.CreateModel(
            name='CommunityBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_bookmarks', to='users.collection')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_bookmarks', to='users.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='community.communitypost')),
            ],
            options={
                'db_table': 'community_bookmark',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='community.communitypost'),
        ),
        migrations.CreateModel(
            name='CommunityReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('useful', 'Useful'), ('agree', 'Agree')], default='like', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.activity')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to='users.collection')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.communitycomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='community.communitypost')),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to='users.review')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_reaction',
            },
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('spoiler', 'Spoiler'), ('illegal', 'Illegal'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.activity')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to='users.collection')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.communitycomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='community.communitypost')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_community_items', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_community_reports', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to='users.review')),
            ],
            options={
                'db_table': 'community_report',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('followed', 'Followed'), ('commented', 'Commented'), ('reacted', 'Reacted'), ('mentioned', 'Mentioned')], max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.activity')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.collection')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.communitycomment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='community.communitypost')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.review')),
            ],
            options={
                'db_table': 'community_notification',
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_relations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_user_block',
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_relations', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_user_follow',
            },
        ),
        migrations.CreateModel(
            name='UserMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by_relations', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muting_relations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'community_user_mute',
            },
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['author', '-created_at'], name='idx_cp_author_created'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['subject', '-last_activity_at'], name='idx_cp_subject_active'),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['visibility', 'feed_policy', '-created_at'], name='idx_cp_feed'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['author', '-created_at'], name='idx_cc_author_created'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['post', '-created_at'], name='idx_cc_post_created'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['review', '-created_at'], name='idx_cc_review_created'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['collection', '-created_at'], name='idx_cc_collection_created'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['activity', '-created_at'], name='idx_cc_activity_created'),
        ),
        migrations.AddIndex(
            model_name='communitycomment',
            index=models.Index(fields=['parent', '-created_at'], name='idx_cc_parent_created'),
        ),
        migrations.AddConstraint(
            model_name='communitycomment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', True), ('collection__isnull', True), ('post__isnull', False), ('review__isnull', True)), models.Q(('activity__isnull', True), ('collection__isnull', True), ('post__isnull', True), ('review__isnull', False)), models.Q(('activity__isnull', True), ('collection__isnull', False), ('post__isnull', True), ('review__isnull', True)), models.Q(('activity__isnull', False), ('collection__isnull', True), ('post__isnull', True), ('review__isnull', True)), _connector='OR'), name='ck_c_comment_single_target'),
        ),
        migrations.AddIndex(
            model_name='communitybookmark',
            index=models.Index(fields=['user', '-created_at'], name='idx_cb_user_created'),
        ),
        migrations.AddConstraint(
            model_name='communitybookmark',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('collection__isnull', True), ('post__isnull', False), ('review__isnull', True)), models.Q(('collection__isnull', True), ('post__isnull', True), ('review__isnull', False)), models.Q(('collection__isnull', False), ('post__isnull', True), ('review__isnull', True)), _connector='OR'), name='ck_c_bookmark_single_target'),
        ),
        migrations.AddConstraint(
            model_name='communitybookmark',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='uq_c_bookmark_post'),
        ),
        migrations.AddConstraint(
            model_name='communitybookmark',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='uq_c_bookmark_review'),
        ),
        migrations.AddConstraint(
            model_name='communitybookmark',
            constraint=models.UniqueConstraint(fields=('user', 'collection'), name='uq_c_bookmark_collection'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['user', '-created_at'], name='idx_ca_user_created'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', '-created_at'], name='idx_ca_type_created'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['visibility', 'feed_policy', '-created_at'], name='idx_ca_feed'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['group_key', '-created_at'], name='idx_ca_group_created'),
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='uq_c_activity_dedupe_key'),
        ),
        migrations.AddIndex(
            model_name='communityreaction',
            index=models.Index(fields=['user', '-created_at'], name='idx_cr_user_created'),
        ),
        migrations.AddIndex(
            model_name='communityreaction',
            index=models.Index(fields=['reaction_type', '-created_at'], name='idx_cr_type_created'),
        ),
        migrations.AddConstraint(
            model_name='communityreaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', True), ('collection__isnull', True), ('comment__isnull', True), ('post__isnull', False), ('review__isnull', True)), models.Q(('activity__isnull', True), ('collection__isnull', True), ('comment__isnull', False), ('post__isnull', True), ('review__isnull', True)), models.Q(('activity__isnull', True), ('collection__isnull', True), ('comment__isnull', True), ('post__isnull', True), ('review__isnull', False)), models.Q(('activity__isnull', True), ('collection__isnull', False), ('comment__isnull', True), ('post__isnull', True), ('review__isnull', True)), models.Q(('activity__isnull', False), ('collection__isnull', True), ('comment__isnull', True), ('post__isnull', True), ('review__isnull', True)), _connector='OR'), name='ck_c_reaction_single_target'),
        ),
        migrations.AddConstraint(
            model_name='communityreaction',
            constraint=models.UniqueConstraint(fields=('user', 'post', 'reaction_type'), name='uq_c_reaction_post'),
        ),
        migrations.AddConstraint(
            model_name='communityreaction',
            constraint=models.UniqueConstraint(fields=('user', 'comment', 'reaction_type'), name='uq_c_reaction_comment'),
        ),
        migrations.AddConstraint(
            model_name='communityreaction',
            constraint=models.UniqueConstraint(fields=('user', 'review', 'reaction_type'), name='uq_c_reaction_review'),
        ),
        migrations.AddConstraint(
            model_name='communityreaction',
            constraint=models.UniqueConstraint(fields=('user', 'collection', 'reaction_type'), name='uq_c_reaction_collection'),
        ),
        migrations.AddConstraint(
            model_name='communityreaction',
            constraint=models.UniqueConstraint(fields=('user', 'activity', 'reaction_type'), name='uq_c_reaction_activity'),
        ),
        migrations.AddIndex(
            model_name='communityreport',
            index=models.Index(fields=['status', '-created_at'], name='idx_creport_status_created'),
        ),
        migrations.AddIndex(
            model_name='communityreport',
            index=models.Index(fields=['reporter', '-created_at'], name='idx_creport_reporter_created'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read_at', '-created_at'], name='idx_cn_recipient_read'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='idx_cn_recipient_created'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['user', '-created_at'], name='idx_cub_user_created'),
        ),
        migrations.AddIndex(
            model_name='userblock',
            index=models.Index(fields=['blocked_user'], name='idx_cub_blocked_user'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('user', 'blocked_user'), name='uq_c_user_block'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('blocked_user')), _negated=True), name='ck_c_no_self_block'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['follower', '-created_at'], name='idx_cuf_follower_created'),
        ),
        migrations.AddIndex(
            model_name='userfollow',
            index=models.Index(fields=['following', '-created_at'], name='idx_cuf_following_created'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='uq_c_follow'),
        ),
        migrations.AddConstraint(
            model_name='userfollow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('following')), _negated=True), name='ck_c_no_self_follow'),
        ),
        migrations.AddIndex(
            model_name='usermute',
            index=models.Index(fields=['user', '-created_at'], name='idx_cum_user_created'),
        ),
        migrations.AddIndex(
            model_name='usermute',
            index=models.Index(fields=['muted_user'], name='idx_cum_muted_user'),
        ),
        migrations.AddConstraint(
            model_name='usermute',
            constraint=models.UniqueConstraint(fields=('user', 'muted_user'), name='uq_c_user_mute'),
        ),
        migrations.AddConstraint(
            model_name='usermute',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('muted_user')), _negated=True), name='ck_c_no_self_mute'),
        ),
    ]
