# Generated by Django 5.2.7 on 2026-06-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_moderationaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
