# Generated by Django 5.2.7 on 2026-06-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_communitycomment_reply_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycomment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communitycomment',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
