# Generated by Django 5.2.16 on 2026-08-12 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_enforce_content_invariants'),
        ('index', '0008_airingevent_appearance_contentrating_entity_credit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='communitypost',
            name='ck_c_post_type_subject',
        ),
        migrations.AddField(
            model_name='activity',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='index.entity'),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='community_posts', to='index.entity'),
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(choices=[('status', 'Status'), ('entity', 'Entity'), ('subject', 'Legacy subject')], default='status', max_length=16),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['entity', '-last_activity_at'], name='idx_cp_entity_active'),
        ),
        migrations.AddConstraint(
            model_name='communitypost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entity__isnull', False), ('post_type', 'entity')), models.Q(('post_type', 'subject'), ('subject__isnull', False)), models.Q(('entity__isnull', True), ('post_type', 'status'), ('subject__isnull', True)), _connector='OR'), name='ck_c_post_type_target'),
        ),
    ]
