# Generated by Django 5.2.17 on 2026-08-21 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_communitypost_ck_c_post_type_subject_and_more'),
        ('index', '0016_term_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='communitypost',
            name='ck_c_post_type_target',
        ),
        migrations.RemoveIndex(
            model_name='communitypost',
            name='idx_cp_subject_active',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='subject',
        ),
        migrations.AlterField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(choices=[('status', 'Status'), ('entity', 'Entity')], default='status', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='communitypost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('entity__isnull', False), ('post_type', 'entity')), models.Q(('entity__isnull', True), ('post_type', 'status')), _connector='OR'), name='ck_c_post_type_target'),
        ),
    ]
