# Generated by Django 5.2.7 on 2026-04-02 01:10

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('info_source', models.CharField(max_length=64)),
                ('id_source', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_type', models.CharField(blank=True, choices=[('anime', 'Anime'), ('galgame', 'Galgame'), ('game', 'Game'), ('manga', 'Manga'), ('novel', 'Novel'), ('book', 'Book'), ('music', 'Music'), ('other', 'Other')], max_length=64)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('title_cn', models.CharField(blank=True, max_length=256)),
                ('date', models.DateField(blank=True, null=True)),
                ('image_original', models.URLField(blank=True, max_length=1024)),
                ('image_thumbnail', models.URLField(blank=True, max_length=1024)),
                ('platform', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('nsfw', models.BooleanField(default=False)),
                ('series', models.BooleanField(default=False)),
                ('volumes', models.IntegerField(blank=True, null=True)),
                ('eps', models.IntegerField(blank=True, null=True)),
                ('total_episodes', models.IntegerField(blank=True, null=True)),
                ('infobox', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_source', models.CharField(max_length=64)),
                ('id_source', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=64)),
                ('birth', models.JSONField(blank=True, default=dict)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('blood_type', models.CharField(blank=True, max_length=64)),
                ('image_original', models.URLField(blank=True, max_length=1024)),
                ('image_thumbnail', models.URLField(blank=True, max_length=1024)),
                ('infobox', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_source', models.CharField(max_length=64)),
                ('id_source', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=64)),
                ('birth', models.JSONField(blank=True, default=dict)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('career', models.JSONField(blank=True, default=list)),
                ('image_original', models.URLField(blank=True, max_length=1024)),
                ('image_thumbnail', models.URLField(blank=True, max_length=1024)),
                ('infobox', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('info_source', models.CharField(max_length=64)),
                ('id_source', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='anime', serialize=False, to='index.subject')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None)),
                ('titles', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('anime_type', models.CharField(blank=True, max_length=64)),
                ('anime_source', models.CharField(blank=True, max_length=64)),
                ('official_websites', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('image_original', models.URLField(blank=True, max_length=1024)),
                ('image_thumbnail', models.URLField(blank=True, max_length=1024)),
                ('image_extra', models.JSONField(blank=True, default=list)),
                ('anime_status', models.CharField(blank=True, max_length=256)),
                ('ep_total', models.IntegerField(blank=True, null=True)),
                ('broadcast', models.JSONField(blank=True, default=dict)),
                ('broadcast_season', models.JSONField(blank=True, default=dict)),
                ('external_links', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'anime',
            },
        ),
        migrations.CreateModel(
            name='Galgame',
            fields=[
                ('info_source', models.CharField(max_length=64)),
                ('id_source', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='galgame', serialize=False, to='index.subject')),
                ('aliases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None)),
                ('titles', models.JSONField(blank=True, default=dict)),
                ('released_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image_original', models.URLField(blank=True, max_length=1024)),
                ('image_thumbnail', models.URLField(blank=True, max_length=1024)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('platforms', models.JSONField(blank=True, default=list)),
                ('galgame_status', models.CharField(blank=True, max_length=64)),
                ('external_links', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'galgame',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_source', models.CharField(max_length=64)),
                ('id_source', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('type', models.CharField(blank=True, max_length=64)),
                ('ep_num', models.IntegerField(blank=True, null=True)),
                ('sort', models.IntegerField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='index.subject')),
            ],
            options={
                'db_table': 'episode',
            },
        ),
        migrations.CreateModel(
            name='SubjectCharacterRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=256)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relations', to='index.character')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_relations', to='index.subject')),
            ],
            options={
                'db_table': 'subject_character_relation',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='subjects', through='index.SubjectCharacterRelation', to='index.character'),
        ),
        migrations.CreateModel(
            name='SubjectStaffRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=256)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relations', to='index.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_relations', to='index.subject')),
            ],
            options={
                'db_table': 'subject_staff_relation',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='subjects', through='index.SubjectStaffRelation', to='index.staff'),
        ),
        migrations.CreateModel(
            name='SubjectSubjectRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, max_length=256)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='index.subject')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='index.subject')),
            ],
            options={
                'db_table': 'subject_subject_relation',
            },
        ),
        migrations.CreateModel(
            name='AnimeGenreRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_relations', to='index.genre')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_relations', to='index.anime')),
            ],
            options={
                'db_table': 'anime_genre_relation',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='animes', through='index.AnimeGenreRelation', to='index.genre'),
        ),
        migrations.CreateModel(
            name='GalgameGenreRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galgame_relations', to='index.genre')),
                ('galgame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_relations', to='index.galgame')),
            ],
            options={
                'db_table': 'galgame_genre_relation',
            },
        ),
        migrations.AddField(
            model_name='galgame',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='galgames', through='index.GalgameGenreRelation', to='index.genre'),
        ),
        migrations.CreateModel(
            name='SubjectCharacterActorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_roles', to='index.staff')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_relations', to='index.character')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_actor_relations', to='index.subject')),
            ],
            options={
                'db_table': 'subject_character_actor_relation',
                'indexes': [models.Index(fields=['subject', 'character'], name='idx_subj_char_act_sc'), models.Index(fields=['character', 'actor'], name='idx_subj_char_act_ca')],
                'constraints': [models.UniqueConstraint(fields=('subject', 'character', 'actor'), name='uq_subject_character_actor')],
            },
        ),
        migrations.AddIndex(
            model_name='subjectcharacterrelation',
            index=models.Index(fields=['subject', 'role'], name='idx_subj_char_sr'),
        ),
        migrations.AddConstraint(
            model_name='subjectcharacterrelation',
            constraint=models.UniqueConstraint(fields=('subject', 'character', 'role'), name='uq_subject_character_role'),
        ),
        migrations.AddIndex(
            model_name='subjectstaffrelation',
            index=models.Index(fields=['subject', 'role'], name='idx_subj_stf_sr'),
        ),
        migrations.AddConstraint(
            model_name='subjectstaffrelation',
            constraint=models.UniqueConstraint(fields=('subject', 'staff', 'role'), name='uq_subject_staff_role'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='idx_subject_title', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='subjectsubjectrelation',
            index=models.Index(fields=['source', 'relation'], name='idx_subj_subj_sr'),
        ),
        migrations.AddIndex(
            model_name='subjectsubjectrelation',
            index=models.Index(fields=['target'], name='idx_subj_subj_t'),
        ),
        migrations.AddConstraint(
            model_name='subjectsubjectrelation',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relation'), name='uq_subject_subject_relation'),
        ),
        migrations.AlterUniqueTogether(
            name='animegenrerelation',
            unique_together={('anime', 'genre')},
        ),
        migrations.AddIndex(
            model_name='anime',
            index=django.contrib.postgres.indexes.GinIndex(fields=['aliases'], name='idx_anime_aliases'),
        ),
        migrations.AlterUniqueTogether(
            name='galgamegenrerelation',
            unique_together={('galgame', 'genre')},
        ),
        migrations.AddIndex(
            model_name='galgame',
            index=django.contrib.postgres.indexes.GinIndex(fields=['aliases'], name='idx_galgame_aliases'),
        ),
    ]
