# Generated by Django 5.2.7 on 2026-05-11 09:25

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
    ]
