# Generated by Django 5.2.7 on 2026-05-25 07:05

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_cn'], name='idx_subject_title_cn', opclasses=['gin_trgm_ops']),
        ),
    ]
