# Generated by Django 5.2.7 on 2026-05-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_subject_idx_subject_title_cn'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday_en', models.CharField(blank=True, max_length=16)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entry', to='index.subject')),
            ],
            options={
                'db_table': 'calendar_subject',
                'indexes': [models.Index(fields=['weekday_en'], name='idx_cal_weekday_en')],
            },
        ),
    ]
