# Generated by Django 5.2.16 on 2026-08-11 08:48

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_enforce_source_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiringEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('region', models.CharField(blank=True, max_length=16)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('precision', models.CharField(choices=[('minute', 'Minute'), ('day', 'Day'), ('weekday', 'Weekday'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('raw_value', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'airing_event',
            },
        ),
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=128)),
                ('spoiler_level', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'appearance',
            },
        ),
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
                ('region', models.CharField(blank=True, max_length=16)),
                ('minimum_age', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_rating',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('work', 'Work'), ('release', 'Release'), ('episode', 'Episode'), ('contributor', 'Contributor'), ('character', 'Character'), ('unclassified', 'Unclassified')], max_length=32)),
                ('lifecycle', models.CharField(choices=[('active', 'Active'), ('merged', 'Merged'), ('retired', 'Retired')], default='active', max_length=16)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('authenticated', 'Authenticated'), ('restricted', 'Restricted')], default='public', max_length=16)),
                ('audience', models.CharField(choices=[('unknown', 'Unknown'), ('general', 'General'), ('adult', 'Adult')], default='unknown', max_length=16)),
                ('spoiler_level', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'index_entity',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=256)),
                ('credited_as', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'credit',
            },
        ),
        migrations.CreateModel(
            name='EntityDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('language', models.CharField(blank=True, max_length=35)),
                ('is_official', models.BooleanField(default=False)),
                ('is_machine_generated', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('spoiler_level', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'entity_description',
            },
        ),
        migrations.CreateModel(
            name='EntityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(blank=True, max_length=32)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'entity_media',
            },
        ),
        migrations.CreateModel(
            name='EntityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=512)),
                ('language', models.CharField(blank=True, max_length=35)),
                ('script', models.CharField(blank=True, max_length=4)),
                ('region', models.CharField(blank=True, max_length=3)),
                ('kind', models.CharField(choices=[('original', 'Original'), ('official', 'Official'), ('alias', 'Alias'), ('short', 'Short'), ('romanized', 'Romanized'), ('translated', 'Translated')], max_length=16)),
                ('is_official', models.BooleanField(default=False)),
                ('is_original', models.BooleanField(default=False)),
                ('is_machine_generated', models.BooleanField(default=False)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'entity_name',
            },
        ),
        migrations.CreateModel(
            name='EntityRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'entity_redirect',
            },
        ),
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.SlugField(max_length=128)),
                ('qualifiers', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'entity_relation',
            },
        ),
        migrations.CreateModel(
            name='EntityRelationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('json_pointer', models.CharField(blank=True, max_length=512)),
                ('raw_relation', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'entity_relation_evidence',
            },
        ),
        migrations.CreateModel(
            name='EntityTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('spoiler_level', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'entity_term',
            },
        ),
        migrations.CreateModel(
            name='EpisodeExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_method', models.CharField(choices=[('legacy', 'Legacy backfill'), ('provider', 'Provider record'), ('external_id', 'Verified external ID'), ('manual', 'Manual'), ('reviewed_ai', 'Reviewed AI proposal')], max_length=16)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_primary', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'episode_external_identity',
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(max_length=2048)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('link_type', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'external_link',
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('value_hash', models.CharField(max_length=64)),
                ('language', models.CharField(blank=True, max_length=35)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='candidate', max_length=16)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('spoiler_level', models.PositiveSmallIntegerField(default=0)),
                ('is_machine_generated', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fact',
            },
        ),
        migrations.CreateModel(
            name='FactEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('json_pointer', models.CharField(blank=True, max_length=512)),
                ('note', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'fact_evidence',
            },
        ),
        migrations.CreateModel(
            name='IndexCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'index_collection',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='IndexMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing_state', models.CharField(choices=[('listed', 'Listed'), ('unlisted', 'Unlisted'), ('suppressed', 'Suppressed')], default='listed', max_length=16)),
                ('inclusion_reason', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'index_membership',
            },
        ),
        migrations.CreateModel(
            name='MappingRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapper', models.CharField(max_length=128)),
                ('mapper_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=16)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mapping_run',
            },
        ),
        migrations.CreateModel(
            name='MatchCandidate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('runner_up_margin', models.DecimalField(decimal_places=4, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('policy_version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('abstained', 'Abstained')], default='pending', max_length=16)),
                ('hard_conflicts', models.JSONField(blank=True, default=list)),
            ],
            options={
                'db_table': 'match_candidate',
            },
        ),
        migrations.CreateModel(
            name='MatchDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(choices=[('bind', 'Bind'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=16)),
                ('decided_by', models.CharField(max_length=32)),
                ('policy_version', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('decision_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'match_decision',
            },
        ),
        migrations.CreateModel(
            name='MatchEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(max_length=64)),
                ('value', models.JSONField()),
                ('weight', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
            ],
            options={
                'db_table': 'match_evidence',
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('media_type', models.CharField(blank=True, max_length=64)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('safety', models.CharField(choices=[('safe', 'Safe'), ('suggestive', 'Suggestive'), ('explicit', 'Explicit'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('spoiler_level', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'media_asset',
            },
        ),
        migrations.CreateModel(
            name='MergeEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('rule', 'Rule'), ('ai_policy', 'AI policy'), ('manual', 'Manual')], max_length=16)),
                ('reason', models.TextField()),
                ('snapshot', models.JSONField(default=dict)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entity_merge_event',
            },
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('sample_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'metric_snapshot',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin', models.CharField(choices=[('mapped', 'Mapped'), ('legacy', 'Legacy'), ('manual', 'Manual')], max_length=16)),
                ('schema_name', models.CharField(max_length=128)),
                ('schema_version', models.CharField(max_length=64)),
                ('normalized_data', models.JSONField()),
                ('normalized_hash', models.CharField(max_length=64)),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'provider_observation',
            },
        ),
        migrations.CreateModel(
            name='Predicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('value_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('entity', 'Entity'), ('json', 'JSON')], max_length=16)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'predicate',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('base_url', models.URLField(blank=True, max_length=1024)),
                ('terms_url', models.URLField(blank=True, max_length=1024)),
                ('attribution_url', models.URLField(blank=True, max_length=1024)),
                ('license_name', models.CharField(blank=True, max_length=128)),
                ('storage_policy', models.CharField(choices=[('unknown', 'Unknown'), ('allowed', 'Allowed'), ('restricted', 'Restricted'), ('forbidden', 'Forbidden')], default='unknown', max_length=16)),
                ('redistribution_policy', models.CharField(choices=[('unknown', 'Unknown'), ('allowed', 'Allowed'), ('restricted', 'Restricted'), ('forbidden', 'Forbidden')], default='unknown', max_length=16)),
                ('commercial_use_policy', models.CharField(choices=[('unknown', 'Unknown'), ('allowed', 'Allowed'), ('restricted', 'Restricted'), ('forbidden', 'Forbidden')], default='unknown', max_length=16)),
                ('ai_usage_policy', models.CharField(choices=[('unknown', 'Unknown'), ('allowed', 'Allowed'), ('restricted', 'Restricted'), ('forbidden', 'Forbidden')], default='unknown', max_length=16)),
                ('terms_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'provider',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='ProviderNamespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=64)),
                ('resource_type', models.CharField(choices=[('subject', 'Subject'), ('episode', 'Episode'), ('person', 'Person'), ('character', 'Character'), ('organization', 'Organization'), ('release', 'Release'), ('schedule', 'Schedule'), ('taxonomy', 'Taxonomy')], max_length=32)),
                ('description', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'db_table': 'provider_namespace',
                'ordering': ['provider__slug', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ProviderRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255)),
                ('canonical_url', models.URLField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('active', 'Active'), ('missing', 'Missing'), ('deleted', 'Deleted')], default='active', max_length=16)),
                ('origin', models.CharField(choices=[('legacy', 'Legacy projection'), ('api', 'API'), ('dump', 'Dump'), ('manual', 'Manual')], max_length=16)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_payload_hash', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'provider_record',
            },
        ),
        migrations.CreateModel(
            name='ProviderRepresentation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mapping_kind', models.CharField(choices=[('exact', 'Exact'), ('aggregate', 'Aggregate'), ('partial', 'Partial'), ('variant', 'Variant')], max_length=16)),
                ('method', models.CharField(choices=[('provider', 'Provider'), ('external_id', 'Verified external ID'), ('resolver', 'Resolver'), ('ai', 'AI policy'), ('manual', 'Manual'), ('legacy', 'Legacy backfill')], max_length=16)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'provider_representation',
            },
        ),
        migrations.CreateModel(
            name='ProviderRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('schema_version', models.CharField(blank=True, max_length=64)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('upstream_updated_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'provider_revision',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='RelationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'relation_evidence',
            },
        ),
        migrations.CreateModel(
            name='ReleaseWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('included', 'Included'), ('bonus', 'Bonus')], default='primary', max_length=16)),
            ],
            options={
                'db_table': 'release_work',
            },
        ),
        migrations.CreateModel(
            name='ResolutionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_version', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'resolution_decision',
            },
        ),
        migrations.CreateModel(
            name='SplitEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('restored_snapshot', models.JSONField(default=dict)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'entity_split_event',
            },
        ),
        migrations.CreateModel(
            name='StaffExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_method', models.CharField(choices=[('legacy', 'Legacy backfill'), ('provider', 'Provider record'), ('external_id', 'Verified external ID'), ('manual', 'Manual'), ('reviewed_ai', 'Reviewed AI proposal')], max_length=16)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_primary', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'staff_external_identity',
            },
        ),
        migrations.CreateModel(
            name='SubjectExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_method', models.CharField(choices=[('legacy', 'Legacy backfill'), ('provider', 'Provider record'), ('external_id', 'Verified external ID'), ('manual', 'Manual'), ('reviewed_ai', 'Reviewed AI proposal')], max_length=16)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_primary', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subject_external_identity',
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'taxonomy',
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128)),
            ],
            options={
                'db_table': 'taxonomy_term',
            },
        ),
        migrations.CreateModel(
            name='TermLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=35)),
                ('script', models.CharField(blank=True, max_length=4)),
                ('text', models.CharField(max_length=256)),
                ('is_preferred', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'taxonomy_term_label',
            },
        ),
        migrations.CreateModel(
            name='TermMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5)),
            ],
            options={
                'db_table': 'taxonomy_term_mapping',
            },
        ),
        migrations.CreateModel(
            name='VoicePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(blank=True, max_length=35)),
                ('credited_as', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'db_table': 'voice_performance',
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='disc',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='raw_duration',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_cn',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='episode',
            name='ep_num',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='sort',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='CharacterExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_method', models.CharField(choices=[('legacy', 'Legacy backfill'), ('provider', 'Provider record'), ('external_id', 'Verified external ID'), ('manual', 'Manual'), ('reviewed_ai', 'Reviewed AI proposal')], max_length=16)),
                ('confidence', models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('is_primary', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='index.character')),
            ],
            options={
                'db_table': 'character_external_identity',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='contributor', serialize=False, to='index.entity')),
                ('kind', models.CharField(choices=[('person', 'Person'), ('organization', 'Organization'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
            ],
            options={
                'db_table': 'contributor',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='release', serialize=False, to='index.entity')),
                ('release_type', models.CharField(blank=True, max_length=64)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('date_precision', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year'), ('range', 'Range'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('date_raw', models.CharField(blank=True, max_length=64)),
                ('platform', models.CharField(blank=True, max_length=64)),
                ('region', models.CharField(blank=True, max_length=16)),
                ('is_official', models.BooleanField(blank=True, null=True)),
                ('is_patch', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'release',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='work', serialize=False, to='index.entity')),
                ('work_type', models.CharField(choices=[('anime', 'Anime'), ('galgame', 'Galgame'), ('manga', 'Manga'), ('novel', 'Novel'), ('game', 'Game'), ('music', 'Music'), ('other', 'Other'), ('unclassified', 'Unclassified')], default='unclassified', max_length=32)),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['kind', 'lifecycle'], name='idx_entity_kind_lifecycle'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['visibility', 'audience'], name='idx_entity_visibility_rating'),
        ),
        migrations.AddConstraint(
            model_name='entity',
            constraint=models.CheckConstraint(condition=models.Q(('spoiler_level__lte', 3)), name='ck_entity_spoiler_level'),
        ),
        migrations.AddField(
            model_name='contentrating',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_ratings', to='index.entity'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='character_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_appearances', to='index.entity'),
        ),
        migrations.AddField(
            model_name='airingevent',
            name='episode_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='airing_events', to='index.entity'),
        ),
        migrations.AddField(
            model_name='character',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='character_projection', to='index.entity'),
        ),
        migrations.AddField(
            model_name='episode',
            name='entity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episode_projection', to='index.entity'),
        ),
        migrations.AddField(
            model_name='entitydescription',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='index.entity'),
        ),
        migrations.AddField(
            model_name='entitymedia',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='index.entity'),
        ),
        migrations.AddField(
            model_name='entityname',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='index.entity'),
        ),
        migrations.AddField(
            model_name='entityredirect',
            name='source_entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_redirect', to='index.entity'),
        ),
        migrations.AddField(
            model_name='entityredirect',
            name='target_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_redirects', to='index.entity'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='from_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_entity_relations', to='index.entity'),
        ),
        migrations.AddField(
            model_name='entityrelation',
            name='to_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_entity_relations', to='index.entity'),
        ),
        migrations.AddField(
            model_name='entityrelationevidence',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='index.entityrelation'),
        ),
        migrations.AddField(
            model_name='entityterm',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_links', to='index.entity'),
        ),
        migrations.AddField(
            model_name='episodeexternalidentity',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='index.episode'),
        ),
        migrations.AddField(
            model_name='externallink',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_links', to='index.entity'),
        ),
        migrations.AddField(
            model_name='fact',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='index.entity'),
        ),
        migrations.AddField(
            model_name='factevidence',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='index.fact'),
        ),
        migrations.AddField(
            model_name='indexmembership',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='index.indexcollection'),
        ),
        migrations.AddField(
            model_name='indexmembership',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_memberships', to='index.entity'),
        ),
        migrations.AddField(
            model_name='matchcandidate',
            name='left_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_match_candidates', to='index.entity'),
        ),
        migrations.AddField(
            model_name='matchcandidate',
            name='right_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_match_candidates', to='index.entity'),
        ),
        migrations.AddField(
            model_name='matchdecision',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='index.matchcandidate'),
        ),
        migrations.AddField(
            model_name='matchevidence',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='index.matchcandidate'),
        ),
        migrations.AddField(
            model_name='entitymedia',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='index.mediaasset'),
        ),
        migrations.AddField(
            model_name='mergeevent',
            name='source_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_source_events', to='index.entity'),
        ),
        migrations.AddField(
            model_name='mergeevent',
            name='target_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merge_target_events', to='index.entity'),
        ),
        migrations.AddField(
            model_name='entityredirect',
            name='merge_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='redirect', to='index.mergeevent'),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='index.entity'),
        ),
        migrations.AddField(
            model_name='observation',
            name='mapping_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='index.mappingrun'),
        ),
        migrations.AddField(
            model_name='matchevidence',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='match_evidence', to='index.observation'),
        ),
        migrations.AddField(
            model_name='factevidence',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fact_evidence', to='index.observation'),
        ),
        migrations.AddField(
            model_name='entityterm',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_terms', to='index.observation'),
        ),
        migrations.AddField(
            model_name='entityrelationevidence',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_evidence', to='index.observation'),
        ),
        migrations.AddField(
            model_name='credit',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='index.observation'),
        ),
        migrations.AddField(
            model_name='contentrating',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='content_ratings', to='index.observation'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appearances', to='index.observation'),
        ),
        migrations.AddField(
            model_name='airingevent',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='airing_events', to='index.observation'),
        ),
        migrations.AddField(
            model_name='fact',
            name='predicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facts', to='index.predicate'),
        ),
        migrations.AddField(
            model_name='providernamespace',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='namespaces', to='index.provider'),
        ),
        migrations.AddField(
            model_name='providerrecord',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='index.providernamespace'),
        ),
        migrations.AddField(
            model_name='observation',
            name='provider_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='metricsnapshot',
            name='provider_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metric_snapshots', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='provider_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_assets', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='externallink',
            name='provider_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='external_links', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='episodeexternalidentity',
            name='source_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='entityname',
            name='provider_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_names', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='entitydescription',
            name='provider_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entity_descriptions', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='contentrating',
            name='provider_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_ratings', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='characterexternalidentity',
            name='source_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='providerrepresentation',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_representations', to='index.entity'),
        ),
        migrations.AddField(
            model_name='providerrepresentation',
            name='provider_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representations', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='providerrevision',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='providerrecord',
            name='latest_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='index.providerrevision'),
        ),
        migrations.AddField(
            model_name='mappingrun',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapping_runs', to='index.providerrevision'),
        ),
        migrations.AddField(
            model_name='relationevidence',
            name='character_actor_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='index.subjectcharacteractorrelation'),
        ),
        migrations.AddField(
            model_name='relationevidence',
            name='character_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='index.subjectcharacterrelation'),
        ),
        migrations.AddField(
            model_name='relationevidence',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relation_evidence', to='index.provider'),
        ),
        migrations.AddField(
            model_name='relationevidence',
            name='staff_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='index.subjectstaffrelation'),
        ),
        migrations.AddField(
            model_name='relationevidence',
            name='subject_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='index.subjectsubjectrelation'),
        ),
        migrations.AddField(
            model_name='resolutiondecision',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolution_decisions', to='index.entity'),
        ),
        migrations.AddField(
            model_name='resolutiondecision',
            name='predicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolution_decisions', to='index.predicate'),
        ),
        migrations.AddField(
            model_name='resolutiondecision',
            name='selected_fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_decisions', to='index.fact'),
        ),
        migrations.AddField(
            model_name='splitevent',
            name='merge_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='split_events', to='index.mergeevent'),
        ),
        migrations.AddField(
            model_name='staffexternalidentity',
            name='source_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='staffexternalidentity',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='index.staff'),
        ),
        migrations.AddField(
            model_name='subjectexternalidentity',
            name='source_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='subjectexternalidentity',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_identities', to='index.subject'),
        ),
        migrations.AddField(
            model_name='term',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='index.term'),
        ),
        migrations.AddField(
            model_name='term',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='index.taxonomy'),
        ),
        migrations.AddField(
            model_name='entityterm',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='index.term'),
        ),
        migrations.AddField(
            model_name='termlabel',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='index.term'),
        ),
        migrations.AddField(
            model_name='termmapping',
            name='provider_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taxonomy_mappings', to='index.providerrecord'),
        ),
        migrations.AddField(
            model_name='termmapping',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_mappings', to='index.term'),
        ),
        migrations.AddField(
            model_name='voiceperformance',
            name='appearance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_performances', to='index.appearance'),
        ),
        migrations.AddField(
            model_name='voiceperformance',
            name='observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voice_performances', to='index.observation'),
        ),
        migrations.AddField(
            model_name='voiceperformance',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_performances', to='index.contributor'),
        ),
        migrations.AddField(
            model_name='credit',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='index.contributor'),
        ),
        migrations.AddField(
            model_name='staff',
            name='contributor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_projection', to='index.contributor'),
        ),
        migrations.AddField(
            model_name='releasework',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_links', to='index.release'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.CheckConstraint(condition=models.Q(('date_end__isnull', True), ('date_start__isnull', True), ('date_start__lte', models.F('date_end')), _connector='OR'), name='ck_release_date_range'),
        ),
        migrations.CreateModel(
            name='AnimeProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='anime_profile', serialize=False, to='index.work')),
                ('format', models.CharField(blank=True, max_length=64)),
                ('source_material', models.CharField(blank=True, max_length=128)),
                ('episode_count', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anime_profile',
            },
        ),
        migrations.CreateModel(
            name='GalgameProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='galgame_profile', serialize=False, to='index.work')),
                ('playtime_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('development_status', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'galgame_profile',
            },
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['work_type'], name='idx_work_type'),
        ),
        migrations.AddField(
            model_name='releasework',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_links', to='index.work'),
        ),
        migrations.AddField(
            model_name='credit',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='index.work'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='index.work'),
        ),
        migrations.AddField(
            model_name='airingevent',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airing_events', to='index.work'),
        ),
        migrations.AddIndex(
            model_name='entityrelation',
            index=models.Index(fields=['from_entity', 'relation_type'], name='idx_entity_relation_from'),
        ),
        migrations.AddConstraint(
            model_name='entityrelation',
            constraint=models.UniqueConstraint(fields=('from_entity', 'to_entity', 'relation_type'), name='uq_entity_relation_type'),
        ),
        migrations.AddConstraint(
            model_name='entityrelation',
            constraint=models.CheckConstraint(condition=models.Q(('from_entity', models.F('to_entity')), _negated=True), name='ck_entity_relation_not_self'),
        ),
        migrations.AddIndex(
            model_name='indexmembership',
            index=models.Index(fields=['collection', 'listing_state', '-updated_at'], name='idx_membership_listing'),
        ),
        migrations.AddConstraint(
            model_name='indexmembership',
            constraint=models.UniqueConstraint(fields=('collection', 'entity'), name='uq_index_membership'),
        ),
        migrations.AddIndex(
            model_name='matchcandidate',
            index=models.Index(fields=['status', '-score'], name='idx_match_status_score'),
        ),
        migrations.AddConstraint(
            model_name='matchcandidate',
            constraint=models.UniqueConstraint(fields=('left_entity', 'right_entity', 'policy_version'), name='uq_match_candidate_policy'),
        ),
        migrations.AddConstraint(
            model_name='matchcandidate',
            constraint=models.CheckConstraint(condition=models.Q(('left_entity', models.F('right_entity')), _negated=True), name='ck_match_candidate_not_self'),
        ),
        migrations.AddIndex(
            model_name='matchdecision',
            index=models.Index(fields=['candidate', '-created_at'], name='idx_match_decision_latest'),
        ),
        migrations.AddConstraint(
            model_name='entitymedia',
            constraint=models.UniqueConstraint(fields=('entity', 'asset', 'purpose'), name='uq_entity_media_purpose'),
        ),
        migrations.AddConstraint(
            model_name='mergeevent',
            constraint=models.CheckConstraint(condition=models.Q(('source_entity', models.F('target_entity')), _negated=True), name='ck_merge_event_not_self'),
        ),
        migrations.AddConstraint(
            model_name='entityredirect',
            constraint=models.CheckConstraint(condition=models.Q(('source_entity', models.F('target_entity')), _negated=True), name='ck_entity_redirect_not_self'),
        ),
        migrations.AddConstraint(
            model_name='matchevidence',
            constraint=models.UniqueConstraint(fields=('candidate', 'evidence_type', 'observation'), name='uq_match_evidence_source', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='factevidence',
            constraint=models.UniqueConstraint(fields=('fact', 'observation', 'json_pointer'), name='uq_fact_evidence_pointer'),
        ),
        migrations.AddConstraint(
            model_name='entityrelationevidence',
            constraint=models.UniqueConstraint(fields=('relation', 'observation', 'json_pointer'), name='uq_entity_relation_evidence'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['entity', 'predicate', 'status'], name='idx_fact_resolution'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.UniqueConstraint(fields=('entity', 'predicate', 'value_hash', 'language'), name='uq_fact_value'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(('spoiler_level__lte', 3)), name='ck_fact_spoiler_level'),
        ),
        migrations.AddConstraint(
            model_name='fact',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='ck_fact_confidence'),
        ),
        migrations.AddConstraint(
            model_name='providernamespace',
            constraint=models.UniqueConstraint(fields=('provider', 'slug'), name='uq_provider_namespace_slug'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['provider_record', '-observed_at'], name='idx_observation_record_time'),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.UniqueConstraint(fields=('provider_record', 'mapping_run', 'schema_name', 'normalized_hash'), name='uq_observation_mapping_hash', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='observation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mapping_run__isnull', True), ('origin', 'legacy')), ('mapping_run__isnull', False), _connector='OR'), name='ck_observation_mapping_origin'),
        ),
        migrations.AddIndex(
            model_name='metricsnapshot',
            index=models.Index(fields=['entity', 'metric', '-observed_at'], name='idx_metric_entity_time'),
        ),
        migrations.AddConstraint(
            model_name='metricsnapshot',
            constraint=models.UniqueConstraint(fields=('provider_record', 'metric', 'observed_at'), name='uq_metric_snapshot_time'),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.UniqueConstraint(fields=('url', 'provider_record'), name='uq_media_asset_source', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='mediaasset',
            constraint=models.CheckConstraint(condition=models.Q(('spoiler_level__lte', 3)), name='ck_media_spoiler_level'),
        ),
        migrations.AddConstraint(
            model_name='externallink',
            constraint=models.UniqueConstraint(fields=('entity', 'url', 'provider_record'), name='uq_external_link_source', nulls_distinct=False),
        ),
        migrations.AddIndex(
            model_name='episodeexternalidentity',
            index=models.Index(fields=['episode', 'is_primary'], name='idx_episode_identity_primary'),
        ),
        migrations.AddConstraint(
            model_name='episodeexternalidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('episode',), name='uq_episode_primary_identity'),
        ),
        migrations.AddConstraint(
            model_name='episodeexternalidentity',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='ck_episode_identity_confidence'),
        ),
        migrations.AddIndex(
            model_name='entityname',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text'], name='idx_entity_name_text', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='entityname',
            index=models.Index(fields=['entity', 'language', 'kind'], name='idx_entity_name_language'),
        ),
        migrations.AddConstraint(
            model_name='entityname',
            constraint=models.UniqueConstraint(fields=('entity', 'text', 'language', 'kind', 'provider_record'), name='uq_entity_name_provenance', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='entitydescription',
            constraint=models.CheckConstraint(condition=models.Q(('spoiler_level__lte', 3)), name='ck_description_spoiler_level'),
        ),
        migrations.AddConstraint(
            model_name='entitydescription',
            constraint=models.UniqueConstraint(fields=('entity', 'language', 'provider_record'), name='uq_entity_description_source', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='contentrating',
            constraint=models.UniqueConstraint(fields=('entity', 'system', 'value', 'region', 'provider_record'), name='uq_content_rating_source'),
        ),
        migrations.AddIndex(
            model_name='characterexternalidentity',
            index=models.Index(fields=['character', 'is_primary'], name='idx_character_identity_primary'),
        ),
        migrations.AddConstraint(
            model_name='characterexternalidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('character',), name='uq_character_primary_identity'),
        ),
        migrations.AddConstraint(
            model_name='characterexternalidentity',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='ck_character_identity_confidence'),
        ),
        migrations.AddIndex(
            model_name='providerrepresentation',
            index=models.Index(fields=['provider_record', 'is_active'], name='idx_representation_record'),
        ),
        migrations.AddIndex(
            model_name='providerrepresentation',
            index=models.Index(fields=['entity', 'is_active'], name='idx_representation_entity'),
        ),
        migrations.AddConstraint(
            model_name='providerrepresentation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('provider_record', 'entity', 'mapping_kind'), name='uq_active_provider_representation'),
        ),
        migrations.AddConstraint(
            model_name='providerrepresentation',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='ck_representation_confidence'),
        ),
        migrations.AddIndex(
            model_name='providerrevision',
            index=models.Index(fields=['record', '-fetched_at'], name='idx_provider_revision_fetched'),
        ),
        migrations.AddConstraint(
            model_name='providerrevision',
            constraint=models.UniqueConstraint(fields=('record', 'payload_hash'), name='uq_provider_revision_hash'),
        ),
        migrations.AddIndex(
            model_name='providerrecord',
            index=models.Index(fields=['namespace', 'status'], name='idx_provider_record_ns_status'),
        ),
        migrations.AddIndex(
            model_name='providerrecord',
            index=models.Index(fields=['last_seen_at'], name='idx_provider_record_seen'),
        ),
        migrations.AddConstraint(
            model_name='providerrecord',
            constraint=models.UniqueConstraint(fields=('namespace', 'external_id'), name='uq_provider_record_external_id'),
        ),
        migrations.AddIndex(
            model_name='mappingrun',
            index=models.Index(fields=['revision', 'mapper', '-created_at'], name='idx_mapping_run_revision'),
        ),
        migrations.AddConstraint(
            model_name='relationevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('character_actor_relation__isnull', True), ('character_relation__isnull', True), ('staff_relation__isnull', True), ('subject_relation__isnull', False)), models.Q(('character_actor_relation__isnull', True), ('character_relation__isnull', True), ('staff_relation__isnull', False), ('subject_relation__isnull', True)), models.Q(('character_actor_relation__isnull', True), ('character_relation__isnull', False), ('staff_relation__isnull', True), ('subject_relation__isnull', True)), models.Q(('character_actor_relation__isnull', False), ('character_relation__isnull', True), ('staff_relation__isnull', True), ('subject_relation__isnull', True)), _connector='OR'), name='ck_relation_evidence_single_target'),
        ),
        migrations.AddConstraint(
            model_name='relationevidence',
            constraint=models.UniqueConstraint(fields=('source', 'subject_relation'), name='uq_relation_evidence_subject'),
        ),
        migrations.AddConstraint(
            model_name='relationevidence',
            constraint=models.UniqueConstraint(fields=('source', 'staff_relation'), name='uq_relation_evidence_staff'),
        ),
        migrations.AddConstraint(
            model_name='relationevidence',
            constraint=models.UniqueConstraint(fields=('source', 'character_relation'), name='uq_relation_evidence_character'),
        ),
        migrations.AddConstraint(
            model_name='relationevidence',
            constraint=models.UniqueConstraint(fields=('source', 'character_actor_relation'), name='uq_relation_evidence_actor'),
        ),
        migrations.AddConstraint(
            model_name='resolutiondecision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('entity', 'predicate'), name='uq_active_resolution_decision'),
        ),
        migrations.AddIndex(
            model_name='staffexternalidentity',
            index=models.Index(fields=['staff', 'is_primary'], name='idx_staff_identity_primary'),
        ),
        migrations.AddConstraint(
            model_name='staffexternalidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('staff',), name='uq_staff_primary_identity'),
        ),
        migrations.AddConstraint(
            model_name='staffexternalidentity',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='ck_staff_identity_confidence'),
        ),
        migrations.AddIndex(
            model_name='subjectexternalidentity',
            index=models.Index(fields=['subject', 'is_primary'], name='idx_subject_identity_primary'),
        ),
        migrations.AddConstraint(
            model_name='subjectexternalidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('subject',), name='uq_subject_primary_identity'),
        ),
        migrations.AddConstraint(
            model_name='subjectexternalidentity',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='ck_subject_identity_confidence'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('taxonomy', 'slug'), name='uq_taxonomy_term_slug'),
        ),
        migrations.AddConstraint(
            model_name='entityterm',
            constraint=models.UniqueConstraint(fields=('entity', 'term', 'observation'), name='uq_entity_term_source', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='termlabel',
            constraint=models.UniqueConstraint(fields=('term', 'language', 'script', 'text'), name='uq_term_label'),
        ),
        migrations.AddConstraint(
            model_name='termmapping',
            constraint=models.UniqueConstraint(fields=('term', 'provider_record'), name='uq_term_provider_mapping'),
        ),
        migrations.AddConstraint(
            model_name='voiceperformance',
            constraint=models.UniqueConstraint(fields=('appearance', 'contributor', 'language', 'observation'), name='uq_voice_performance_source', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='releasework',
            constraint=models.UniqueConstraint(fields=('release', 'work', 'role'), name='uq_release_work_role'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(fields=('work', 'contributor', 'role', 'credited_as', 'observation'), name='uq_credit_provenance', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='appearance',
            constraint=models.UniqueConstraint(fields=('work', 'character_entity', 'role', 'observation'), name='uq_appearance_provenance', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='appearance',
            constraint=models.CheckConstraint(condition=models.Q(('spoiler_level__lte', 3)), name='ck_appearance_spoiler_level'),
        ),
        migrations.AddIndex(
            model_name='airingevent',
            index=models.Index(fields=['starts_at'], name='idx_airing_starts_at'),
        ),
        migrations.AddIndex(
            model_name='airingevent',
            index=models.Index(fields=['weekday'], name='idx_airing_weekday'),
        ),
        migrations.AddConstraint(
            model_name='airingevent',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__isnull', True), ('weekday__range', (1, 7)), _connector='OR'), name='ck_airing_weekday'),
        ),
    ]
