# Generated by Django 5.2.16 on 2026-08-12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0008_airingevent_appearance_contentrating_entity_credit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataMigrationRun",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("command", models.CharField(max_length=128)),
                ("version", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("failed", "Failed"),
                            ("succeeded", "Succeeded"),
                        ],
                        max_length=16,
                    ),
                ),
                ("batch_size", models.PositiveIntegerField()),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "data_migration_run",
                "indexes": [
                    models.Index(
                        fields=["command", "status", "-created_at"],
                        name="idx_data_migration_status",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DataMigrationCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stage", models.CharField(max_length=64)),
                ("cursor", models.CharField(blank=True, max_length=512)),
                ("upper_bound", models.CharField(blank=True, max_length=512)),
                ("processed_count", models.PositiveBigIntegerField(default=0)),
                ("is_complete", models.BooleanField(default=False)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="index.datamigrationrun",
                    ),
                ),
            ],
            options={
                "db_table": "data_migration_checkpoint",
                "indexes": [
                    models.Index(
                        fields=["run", "is_complete"],
                        name="idx_data_migration_progress",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "stage"),
                        name="uq_data_migration_checkpoint",
                    )
                ],
            },
        ),
    ]
