# Generated by Django 5.2.16 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


def seed_current_observations(apps, schema_editor):
    CurrentObservation = apps.get_model("index", "CurrentObservation")
    Observation = apps.get_model("index", "Observation")

    candidates = Observation.objects.select_related(
        "mapping_run",
        "provider_record",
    ).order_by("observed_at", "created_at", "pk")
    selected = {}
    for observation in candidates.iterator(chunk_size=1000):
        mapping_run = observation.mapping_run
        if mapping_run is None:
            if observation.provider_record.latest_revision_id is not None:
                continue
            mapper = "legacy"
        else:
            if (
                mapping_run.status != "succeeded"
                or mapping_run.revision_id
                != observation.provider_record.latest_revision_id
            ):
                continue
            mapper = mapping_run.mapper
        selected[(observation.provider_record_id, mapper, observation.schema_name)] = (
            observation
        )

    CurrentObservation.objects.bulk_create(
        [
            CurrentObservation(
                provider_record_id=provider_record_id,
                mapper=mapper,
                schema_name=schema_name,
                observation=observation,
            )
            for (
                provider_record_id,
                mapper,
                schema_name,
            ), observation in selected.items()
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0009_data_migration_checkpoints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providernamespace",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("subject", "Subject"),
                    ("episode", "Episode"),
                    ("person", "Person"),
                    ("character", "Character"),
                    ("organization", "Organization"),
                    ("release", "Release"),
                    ("schedule", "Schedule"),
                    ("taxonomy", "Taxonomy"),
                    ("collection", "Collection snapshot"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="CurrentObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("mapper", models.CharField(max_length=128)),
                ("schema_name", models.CharField(max_length=128)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current_projections",
                        to="index.observation",
                    ),
                ),
                (
                    "provider_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_observations",
                        to="index.providerrecord",
                    ),
                ),
            ],
            options={
                "db_table": "provider_current_observation",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider_record", "mapper", "schema_name"),
                        name="uq_current_observation_mapper",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReleaseWorkEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("json_pointer", models.CharField(blank=True, max_length=512)),
                ("raw_role", models.CharField(blank=True, max_length=64)),
                (
                    "observation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="release_work_evidence",
                        to="index.observation",
                    ),
                ),
                (
                    "release_work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="index.releasework",
                    ),
                ),
            ],
            options={
                "db_table": "release_work_evidence",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("release_work", "observation", "json_pointer"),
                        name="uq_release_work_evidence",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_current_observations, migrations.RunPython.noop),
    ]
