# Generated by Django 5.2.16 on 2026-08-12

import django.db.models.deletion
from django.db import migrations, models


def backfill_current_projection_provenance(apps, schema_editor):
    ContentRating = apps.get_model("index", "ContentRating")
    CurrentObservation = apps.get_model("index", "CurrentObservation")
    EntityDescription = apps.get_model("index", "EntityDescription")
    EntityMedia = apps.get_model("index", "EntityMedia")
    EntityName = apps.get_model("index", "EntityName")
    ExternalLink = apps.get_model("index", "ExternalLink")

    observation_by_record = {}
    ambiguous_records = set()
    for provider_record_id, observation_id in CurrentObservation.objects.values_list(
        "provider_record_id", "observation_id"
    ).iterator(chunk_size=1000):
        previous = observation_by_record.get(provider_record_id)
        if previous is not None and previous != observation_id:
            ambiguous_records.add(provider_record_id)
            continue
        observation_by_record[provider_record_id] = observation_id
    for provider_record_id in ambiguous_records:
        observation_by_record.pop(provider_record_id, None)

    def update_rows(model, *, provider_field):
        pending = []
        for primary_key, provider_record_id in (
            model.objects.filter(
                observation__isnull=True,
                **{f"{provider_field}__isnull": False},
            )
            .values_list("pk", f"{provider_field}_id")
            .iterator(chunk_size=1000)
        ):
            observation_id = observation_by_record.get(provider_record_id)
            if observation_id is None:
                continue
            pending.append(model(pk=primary_key, observation_id=observation_id))
            if len(pending) == 1000:
                model.objects.bulk_update(pending, ["observation"], batch_size=1000)
                pending.clear()
        if pending:
            model.objects.bulk_update(pending, ["observation"], batch_size=1000)

    update_rows(EntityName, provider_field="provider_record")
    update_rows(EntityDescription, provider_field="provider_record")
    update_rows(EntityMedia, provider_field="asset__provider_record")
    update_rows(ExternalLink, provider_field="provider_record")
    update_rows(ContentRating, provider_field="provider_record")


class Migration(migrations.Migration):
    dependencies = [
        ("index", "0010_release_work_evidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="entitydescription",
            name="observation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entity_descriptions",
                to="index.observation",
            ),
        ),
        migrations.AddField(
            model_name="entitymedia",
            name="observation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entity_media",
                to="index.observation",
            ),
        ),
        migrations.AddField(
            model_name="entityname",
            name="observation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entity_names",
                to="index.observation",
            ),
        ),
        migrations.AddField(
            model_name="externallink",
            name="observation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="external_links",
                to="index.observation",
            ),
        ),
        migrations.RunPython(
            backfill_current_projection_provenance,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name="contentrating",
            name="uq_content_rating_source",
        ),
        migrations.RemoveConstraint(
            model_name="entitydescription",
            name="uq_entity_description_source",
        ),
        migrations.RemoveConstraint(
            model_name="entitymedia",
            name="uq_entity_media_purpose",
        ),
        migrations.RemoveConstraint(
            model_name="entityname",
            name="uq_entity_name_provenance",
        ),
        migrations.RemoveConstraint(
            model_name="externallink",
            name="uq_external_link_source",
        ),
        migrations.AddConstraint(
            model_name="contentrating",
            constraint=models.UniqueConstraint(
                fields=(
                    "entity",
                    "system",
                    "value",
                    "region",
                    "provider_record",
                    "observation",
                ),
                name="uq_content_rating_source",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="entitydescription",
            constraint=models.UniqueConstraint(
                fields=("entity", "language", "provider_record", "observation"),
                name="uq_entity_description_source",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymedia",
            constraint=models.UniqueConstraint(
                fields=("entity", "asset", "purpose", "observation"),
                name="uq_entity_media_purpose",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="entityname",
            constraint=models.UniqueConstraint(
                fields=(
                    "entity",
                    "text",
                    "language",
                    "kind",
                    "provider_record",
                    "observation",
                ),
                name="uq_entity_name_provenance",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="externallink",
            constraint=models.UniqueConstraint(
                fields=("entity", "url", "provider_record", "observation"),
                name="uq_external_link_source",
                nulls_distinct=False,
            ),
        ),
    ]
