# Generated by Django 5.2.16 on 2026-08-12 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_field_projection_provenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityredirect',
            name='source_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_redirects', to='index.entity'),
        ),
        migrations.AddConstraint(
            model_name='entityredirect',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('source_entity',), name='uq_active_entity_redirect_source'),
        ),
    ]
