# Generated by Django 5.2.17 on 2026-08-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_remove_animegenrerelation_anime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airingevent',
            name='collection_doing',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
