# Generated by Django 5.2.17 on 2026-08-25 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_airingevent_collection_doing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='termalias',
            name='uq_term_alias_key',
        ),
        migrations.AddField(
            model_name='termalias',
            name='origin',
            field=models.CharField(choices=[('legacy_unknown', 'Legacy provenance unknown'), ('provider', 'Provider mapping'), ('ai_proposal', 'AI proposal'), ('manual', 'Manual')], default='legacy_unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='termalias',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='index.term'),
        ),
        migrations.AddConstraint(
            model_name='termalias',
            constraint=models.UniqueConstraint(fields=('vocabulary', 'normalized_key', 'language', 'provider_namespace'), name='uq_term_alias_key', nulls_distinct=False),
        ),
    ]
