# Generated by Django 5.2.17 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0022_airingboardentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="providerrecord",
            name="raw_state",
            field=models.CharField(
                choices=[
                    ("raw", "Raw payload"),
                    ("slim", "Partial payload"),
                    ("stub", "Identity stub"),
                    ("legacy", "Legacy normalized-only"),
                ],
                default="raw",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="providerrecord",
            index=models.Index(
                fields=["namespace", "raw_state"],
                name="idx_provider_record_raw_state",
            ),
        ),
    ]
