# Generated by Django 5.2.17 on 2026-09-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_providerrecord_raw_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeprofile',
            name='ended_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='animeprofile',
            name='premiered_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
