# Generated by Django 5.2.7 on 2026-04-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_name', models.CharField(max_length=256)),
                ('internal_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'name_mapping',
                'indexes': [models.Index(fields=['external_name'], name='idx_name_mapping')],
                'constraints': [models.UniqueConstraint(fields=('external_name',), name='uq_name_mapping')],
            },
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=256)),
                ('shard', models.CharField(max_length=50)),
                ('current_id', models.IntegerField(default=0)),
                ('end_id', models.IntegerField()),
                ('status', models.CharField(default='running', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sync_state',
                'constraints': [models.UniqueConstraint(fields=('task_name', 'shard'), name='uq_name_shard')],
            },
        ),
    ]
