# Generated by Django 5.2.7 on 2026-04-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=256)),
                ('entity_id', models.IntegerField()),
                ('retry_count', models.IntegerField(default=1)),
                ('first_occurred_at', models.DateTimeField(auto_now_add=True)),
                ('last_occurred_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sync_error',
            },
        ),
        migrations.AddField(
            model_name='syncstate',
            name='fail_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='syncstate',
            name='shard',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='syncstate',
            name='status',
            field=models.CharField(default='running', max_length=256),
        ),
        migrations.AddIndex(
            model_name='syncstate',
            index=models.Index(fields=['task_name', 'shard'], name='idx_name_shard'),
        ),
        migrations.AddIndex(
            model_name='syncerror',
            index=models.Index(fields=['task_name', 'entity_id'], name='idx_name_id'),
        ),
        migrations.AddConstraint(
            model_name='syncerror',
            constraint=models.UniqueConstraint(fields=('task_name', 'entity_id'), name='uq_name_id'),
        ),
    ]
