# Generated by Django 5.2.16 on 2026-08-12 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0004_harden_sync_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='job_type',
            field=models.CharField(choices=[('subject_bangumi', 'Subject by Bangumi'), ('subject_resync', 'Subject resync'), ('vndb_import', 'VNDB import'), ('calendar', 'Calendar'), ('incremental', 'Incremental')], max_length=64),
        ),
    ]
