# Generated by Django 5.2.16 on 2026-08-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0005_alter_syncjob_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='attempt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncjob',
            name='lease_owner',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddIndex(
            model_name='syncjob',
            index=models.Index(fields=['status', 'lease_expires_at'], name='idx_sync_job_lease'),
        ),
    ]
