# Generated by Django 5.2.17 on 2026-08-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0006_syncjob_attempt_syncjob_heartbeat_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NameMapping',
        ),
    ]
