# Generated by Django 5.2.17 on 2026-08-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0007_delete_namemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncjob',
            name='job_type',
            field=models.CharField(choices=[('subject_bangumi', 'Subject by Bangumi'), ('subject_resync', 'Subject resync'), ('vndb_import', 'VNDB import'), ('anilist_import', 'AniList import'), ('calendar', 'Calendar'), ('incremental', 'Incremental')], max_length=64),
        ),
    ]
