# Generated by Django 5.2.17 on 2026-08-25 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_remove_termalias_uq_term_alias_key_termalias_origin_and_more'),
        ('sync', '0008_alter_syncjob_job_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_slug', models.CharField(max_length=64)),
                ('campaign_type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('discovering', 'Discovering'), ('fetching', 'Fetching'), ('mapping', 'Mapping'), ('normalizing', 'Normalizing'), ('reconciling', 'Reconciling'), ('enriching', 'Enriching'), ('reviewing', 'Reviewing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('ai_mode', models.CharField(choices=[('off', 'Off'), ('shadow', 'Shadow'), ('assisted', 'Assisted'), ('required', 'Required')], default='shadow', max_length=16)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('processed_items', models.PositiveIntegerField(default=0)),
                ('synced_items', models.PositiveIntegerField(default=0)),
                ('skipped_items', models.PositiveIntegerField(default=0)),
                ('failed_items', models.PositiveIntegerField(default=0)),
                ('quality_report', models.JSONField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sync_campaign',
                'indexes': [models.Index(fields=['provider_slug', 'status'], name='idx_sync_camp_prov_status'), models.Index(fields=['status', '-created_at'], name='idx_sync_campaign_status')],
            },
        ),
        migrations.CreateModel(
            name='SyncWorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shard', models.PositiveIntegerField(default=0)),
                ('cursor', models.CharField(max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='queued', max_length=16)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('lease_owner', models.CharField(blank=True, max_length=128)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='sync.synccampaign')),
                ('provider_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_work_items', to='index.providerrecord')),
            ],
            options={
                'db_table': 'sync_work_item',
                'indexes': [models.Index(fields=['campaign', 'status'], name='idx_sync_wi_camp_status'), models.Index(fields=['status', 'lease_expires_at'], name='idx_sync_wi_lease')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'shard', 'cursor'), name='uq_sync_work_item_cursor')],
            },
        ),
    ]
