# Generated by Django 5.2.17 on 2026-08-25 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_remove_agentrun_uq_agent_run_idempotency_and_more'),
        ('sync', '0009_synccampaign_syncworkitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccampaign',
            name='agent_run',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_campaign', to='ai.agentrun'),
        ),
    ]
