# Generated by Django 5.2.17 on 2026-08-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_remove_agentrun_uq_agent_run_idempotency_and_more'),
        ('sync', '0010_synccampaign_agent_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccampaign',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='synccampaign',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('provider_slug', 'campaign_type', 'idempotency_key'), name='uq_sync_campaign_idempotency'),
        ),
    ]
