# Generated by Django 5.2.17 on 2026-08-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0011_synccampaign_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncworkitem',
            name='ai_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
