# Generated by Django 5.2.17 on 2026-08-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0012_syncworkitem_ai_processed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='synccampaign',
            name='heartbeat_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synccampaign',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='synccampaign',
            name='lease_owner',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='synccampaign',
            name='next_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncworkitem',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='syncworkitem',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='synccampaign',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('discovering', 'Discovering'), ('fetching', 'Fetching'), ('mapping', 'Mapping'), ('normalizing', 'Normalizing'), ('reconciling', 'Reconciling'), ('enriching', 'Enriching'), ('reviewing', 'Reviewing'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
