# Generated by Django 5.2.17 on 2026-08-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_remove_agentrun_uq_agent_run_idempotency_and_more'),
        ('index', '0019_remove_termalias_uq_term_alias_key_termalias_origin_and_more'),
        ('sync', '0013_harden_campaign_execution'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='synccampaign',
            index=models.Index(fields=['status', 'next_run_at'], name='idx_sync_campaign_next_run'),
        ),
        migrations.AddIndex(
            model_name='synccampaign',
            index=models.Index(fields=['status', 'lease_expires_at'], name='idx_sync_campaign_lease'),
        ),
        migrations.AddIndex(
            model_name='syncworkitem',
            index=models.Index(fields=['campaign', 'status', 'next_retry_at'], name='idx_sync_wi_retry'),
        ),
    ]
