# Generated by Django 5.2.7 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0004_calendarsubject"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarsubject",
            name="collection_doing",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="calendarsubject",
            index=models.Index(
                fields=["weekday_en", "-collection_doing"],
                name="idx_cal_weekday_doing",
            ),
        ),
    ]
